version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    executor: docker
    steps:
      - run: echo "this is the build step"

  deploy-stg:
    executor: docker
    steps:
      - run: echo "this deploys to a staging environment"

  deploy-prd:
    executor: docker
    steps:
      - run: echo "this deploys to the production environment"

workflows:
  build-test-deploy:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 13.11.0
                - 12.16.0
                - 10.19.0
      - build:
          requires:
            - node/test
      - deploy-stg:
          requires:
            - build
      - hold-for-prd:
          type: approval
          requires:
            - deploy-stg
      - deploy-prd:
          requires:
            - hold-for-prd
